"""add_ai_score_last_activity_is_cold_to_leads

Revision ID: 267e68c54a1e
Revises: 943a8df8e42c
Create Date: 2026-06-21 14:57:02.359321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267e68c54a1e'
down_revision: Union[str, None] = '943a8df8e42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('leads', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('is_cold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'is_cold')
    op.drop_column('leads', 'last_activity_at')
    op.drop_column('leads', 'ai_score')
    # ### end Alembic commands ###
