"""add_user_id_to_ai_notes

Revision ID: 3f46db434239
Revises: b87782b91ba4
Create Date: 2026-06-21 13:55:37.308997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f46db434239'
down_revision: Union[str, None] = 'b87782b91ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add as nullable first to handle existing rows
    op.add_column('ai_notes', sa.Column('user_id', sa.UUID(), nullable=True))
    # Delete old notes that have no user (can't be assigned)
    op.execute('DELETE FROM ai_notes WHERE user_id IS NULL')
    # Now make it NOT NULL
    op.alter_column('ai_notes', 'user_id', nullable=False)
    op.create_index(op.f('ix_ai_notes_user_id'), 'ai_notes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_notes', type_='foreignkey')
    op.drop_index(op.f('ix_ai_notes_user_id'), table_name='ai_notes')
    op.drop_column('ai_notes', 'user_id')
    # ### end Alembic commands ###
