"""add_priority_to_followups

Revision ID: 943a8df8e42c
Revises: 3f46db434239
Create Date: 2026-06-21 14:42:20.492035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943a8df8e42c'
down_revision: Union[str, None] = '3f46db434239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followups', sa.Column('priority', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followups', 'priority')
    # ### end Alembic commands ###
